"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class development_command_t(object):

    __slots__ = ["robot_id", "enable_development_mode", "is_rl_mode", "L_Leg_q", "R_Leg_q", "L_Arm_q", "R_Arm_q", "waist_q", "L_Leg_qd", "R_Leg_qd", "L_Arm_qd", "R_Arm_qd", "waist_qd", "L_Leg_tau", "R_Leg_tau", "L_Arm_tau", "R_Arm_tau", "waist_tau", "L_Leg_kp", "R_Leg_kp", "L_Arm_kp", "R_Arm_kp", "waist_kp", "L_Leg_kd", "R_Leg_kd", "L_Arm_kd", "R_Arm_kd", "waist_kd"]

    __typenames__ = ["string", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, [6], [6], [4], [4], None, [6], [6], [4], [4], None, [6], [6], [4], [4], None, [6], [6], [4], [4], None, [6], [6], [4], [4], None]

    def __init__(self):
        self.robot_id = ""
        """
        机器人标识（用于标记目标机器人）
        LCM Type: string
        """

        self.enable_development_mode = 0
        """
        控制标志
        LCM Type: int32_t
        """

        self.is_rl_mode = 0
        """
        1=开始开发模式, 0=结束开发模式
        是否是强化学习模式（1=是，0=否）
        如果是强化学习模式：状态机接手后，对踝关节进行扭矩计算，下发的kp/kd全清零
        如果不是强化学习模式：全部一样赋值（直接使用外部传过来的kp/kd/期望角度/期望速度/期望扭矩）
        LCM Type: int32_t
        """

        self.L_Leg_q = [ 0.0 for dim0 in range(6) ]
        """
        所有关节的期望角度（12腿+9臂=21维）
        LCM Type: float[6]
        """

        self.R_Leg_q = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.waist_q = 0.0
        """ LCM Type: float """
        self.L_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """
        所有关节的期望速度
        LCM Type: float[6]
        """

        self.R_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.waist_qd = 0.0
        """ LCM Type: float """
        self.L_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """
        所有关节的期望扭矩
        LCM Type: float[6]
        """

        self.R_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.waist_tau = 0.0
        """ LCM Type: float """
        self.L_Leg_kp = [ 0.0 for dim0 in range(6) ]
        """
        所有关节的kp
        LCM Type: float[6]
        """

        self.R_Leg_kp = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_kp = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_kp = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.waist_kp = 0.0
        """ LCM Type: float """
        self.L_Leg_kd = [ 0.0 for dim0 in range(6) ]
        """
        所有关节的kd
        LCM Type: float[6]
        """

        self.R_Leg_kd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_kd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_kd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.waist_kd = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(development_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __robot_id_encoded = self.robot_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_id_encoded)+1))
        buf.write(__robot_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ii", self.enable_development_mode, self.is_rl_mode))
        buf.write(struct.pack('>6f', *self.L_Leg_q[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_q[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_q[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_q[:4]))
        buf.write(struct.pack(">f", self.waist_q))
        buf.write(struct.pack('>6f', *self.L_Leg_qd[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_qd[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_qd[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_qd[:4]))
        buf.write(struct.pack(">f", self.waist_qd))
        buf.write(struct.pack('>6f', *self.L_Leg_tau[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_tau[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_tau[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_tau[:4]))
        buf.write(struct.pack(">f", self.waist_tau))
        buf.write(struct.pack('>6f', *self.L_Leg_kp[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_kp[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_kp[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_kp[:4]))
        buf.write(struct.pack(">f", self.waist_kp))
        buf.write(struct.pack('>6f', *self.L_Leg_kd[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_kd[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_kd[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_kd[:4]))
        buf.write(struct.pack(">f", self.waist_kd))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != development_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return development_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = development_command_t()
        __robot_id_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_id = buf.read(__robot_id_len)[:-1].decode('utf-8', 'replace')
        self.enable_development_mode, self.is_rl_mode = struct.unpack(">ii", buf.read(8))
        self.L_Leg_q = struct.unpack('>6f', buf.read(24))
        self.R_Leg_q = struct.unpack('>6f', buf.read(24))
        self.L_Arm_q = struct.unpack('>4f', buf.read(16))
        self.R_Arm_q = struct.unpack('>4f', buf.read(16))
        self.waist_q = struct.unpack(">f", buf.read(4))[0]
        self.L_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.R_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.L_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.R_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.waist_qd = struct.unpack(">f", buf.read(4))[0]
        self.L_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.R_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.L_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.R_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.waist_tau = struct.unpack(">f", buf.read(4))[0]
        self.L_Leg_kp = struct.unpack('>6f', buf.read(24))
        self.R_Leg_kp = struct.unpack('>6f', buf.read(24))
        self.L_Arm_kp = struct.unpack('>4f', buf.read(16))
        self.R_Arm_kp = struct.unpack('>4f', buf.read(16))
        self.waist_kp = struct.unpack(">f", buf.read(4))[0]
        self.L_Leg_kd = struct.unpack('>6f', buf.read(24))
        self.R_Leg_kd = struct.unpack('>6f', buf.read(24))
        self.L_Arm_kd = struct.unpack('>4f', buf.read(16))
        self.R_Arm_kd = struct.unpack('>4f', buf.read(16))
        self.waist_kd = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if development_command_t in parents: return 0
        tmphash = (0xad2ffdedbfbd6148) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if development_command_t._packed_fingerprint is None:
            development_command_t._packed_fingerprint = struct.pack(">Q", development_command_t._get_hash_recursive([]))
        return development_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", development_command_t._get_packed_fingerprint())[0]

