"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class development_state_t(object):

    __slots__ = ["robot_id", "L_Leg_q", "R_Leg_q", "L_Arm_q", "R_Arm_q", "L_Leg_qd", "R_Leg_qd", "L_Arm_qd", "R_Arm_qd", "L_Leg_tau", "R_Leg_tau", "L_Arm_tau", "R_Arm_tau", "Head_q", "Head_qd", "Head_tau", "waist_q", "waist_qd", "waist_tau", "quat", "rpy", "omega", "acc", "v_des", "omega_des", "mode"]

    __typenames__ = ["string", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t"]

    __dimensions__ = [None, [6], [6], [4], [4], [6], [6], [4], [4], [6], [6], [4], [4], None, None, None, None, None, None, [4], [3], [3], [3], [3], [3], None]

    def __init__(self):
        self.robot_id = ""
        """
        机器人标识（用于标记机器人型号）
        LCM Type: string
        """

        self.L_Leg_q = [ 0.0 for dim0 in range(6) ]
        """
        关节状态（与humanoid_joint_state_t相同）
        LCM Type: float[6]
        """

        self.R_Leg_q = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.Head_q = 0.0
        """ LCM Type: float """
        self.Head_qd = 0.0
        """ LCM Type: float """
        self.Head_tau = 0.0
        """ LCM Type: float """
        self.waist_q = 0.0
        """ LCM Type: float """
        self.waist_qd = 0.0
        """ LCM Type: float """
        self.waist_tau = 0.0
        """ LCM Type: float """
        self.quat = [ 0.0 for dim0 in range(4) ]
        """
        IMU数据（与microstrain_lcmt相同）
        LCM Type: float[4]
        """

        self.rpy = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.omega = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.acc = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.v_des = [ 0.0 for dim0 in range(3) ]
        """
        遥控器指令
        LCM Type: float[3]
        """

        self.omega_des = [ 0.0 for dim0 in range(3) ]
        """
        期望速度 [vx, vy, omega_z]
        LCM Type: float[3]
        """

        self.mode = 0
        """
        期望角速度
        LCM Type: int32_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(development_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __robot_id_encoded = self.robot_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_id_encoded)+1))
        buf.write(__robot_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>6f', *self.L_Leg_q[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_q[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_q[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_q[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_qd[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_qd[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_qd[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_qd[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_tau[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_tau[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_tau[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_tau[:4]))
        buf.write(struct.pack(">ffffff", self.Head_q, self.Head_qd, self.Head_tau, self.waist_q, self.waist_qd, self.waist_tau))
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack('>3f', *self.omega[:3]))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack('>3f', *self.v_des[:3]))
        buf.write(struct.pack('>3f', *self.omega_des[:3]))
        buf.write(struct.pack(">i", self.mode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != development_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return development_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = development_state_t()
        __robot_id_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_id = buf.read(__robot_id_len)[:-1].decode('utf-8', 'replace')
        self.L_Leg_q = struct.unpack('>6f', buf.read(24))
        self.R_Leg_q = struct.unpack('>6f', buf.read(24))
        self.L_Arm_q = struct.unpack('>4f', buf.read(16))
        self.R_Arm_q = struct.unpack('>4f', buf.read(16))
        self.L_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.R_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.L_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.R_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.L_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.R_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.L_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.R_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.Head_q, self.Head_qd, self.Head_tau, self.waist_q, self.waist_qd, self.waist_tau = struct.unpack(">ffffff", buf.read(24))
        self.quat = struct.unpack('>4f', buf.read(16))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.omega = struct.unpack('>3f', buf.read(12))
        self.acc = struct.unpack('>3f', buf.read(12))
        self.v_des = struct.unpack('>3f', buf.read(12))
        self.omega_des = struct.unpack('>3f', buf.read(12))
        self.mode = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if development_state_t in parents: return 0
        tmphash = (0x62b7581da5dd9e39) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if development_state_t._packed_fingerprint is None:
            development_state_t._packed_fingerprint = struct.pack(">Q", development_state_t._get_hash_recursive([]))
        return development_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", development_state_t._get_packed_fingerprint())[0]

