"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class humanoid_joint_command_t(object):

    __slots__ = ["L_Leg_q", "R_Leg_q", "L_Arm_q", "R_Arm_q", "L_Leg_qd", "R_Leg_qd", "L_Arm_qd", "R_Arm_qd", "L_Leg_tau", "R_Leg_tau", "L_Arm_tau", "R_Arm_tau", "L_Leg_kp", "R_Leg_kp", "L_Arm_kp", "R_Arm_kp", "L_Leg_kd", "R_Leg_kd", "L_Arm_kd", "R_Arm_kd", "Head_q", "Head_qd", "Head_tau", "Head_kp", "Head_kd", "waist_q", "waist_qd", "waist_tau", "waist_kp", "waist_kd", "reserved1", "reserved2", "reserved3", "reserved4", "reserved5"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t", "int32_t", "int32_t", "int32_t", "int32_t"]

    __dimensions__ = [[6], [6], [4], [4], [6], [6], [4], [4], [6], [6], [4], [4], [6], [6], [4], [4], [6], [6], [4], [4], None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.L_Leg_q = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_q = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_q = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_qd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_qd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_tau = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_kp = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_kp = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_kp = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_kp = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.L_Leg_kd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.R_Leg_kd = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.L_Arm_kd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.R_Arm_kd = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.Head_q = 0.0
        """ LCM Type: float """
        self.Head_qd = 0.0
        """ LCM Type: float """
        self.Head_tau = 0.0
        """ LCM Type: float """
        self.Head_kp = 0.0
        """ LCM Type: float """
        self.Head_kd = 0.0
        """ LCM Type: float """
        self.waist_q = 0.0
        """ LCM Type: float """
        self.waist_qd = 0.0
        """ LCM Type: float """
        self.waist_tau = 0.0
        """ LCM Type: float """
        self.waist_kp = 0.0
        """ LCM Type: float """
        self.waist_kd = 0.0
        """ LCM Type: float """
        self.reserved1 = 0
        """ LCM Type: int32_t """
        self.reserved2 = 0
        """ LCM Type: int32_t """
        self.reserved3 = 0
        """ LCM Type: int32_t """
        self.reserved4 = 0
        """ LCM Type: int32_t """
        self.reserved5 = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(humanoid_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6f', *self.L_Leg_q[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_q[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_q[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_q[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_qd[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_qd[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_qd[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_qd[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_tau[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_tau[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_tau[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_tau[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_kp[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_kp[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_kp[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_kp[:4]))
        buf.write(struct.pack('>6f', *self.L_Leg_kd[:6]))
        buf.write(struct.pack('>6f', *self.R_Leg_kd[:6]))
        buf.write(struct.pack('>4f', *self.L_Arm_kd[:4]))
        buf.write(struct.pack('>4f', *self.R_Arm_kd[:4]))
        buf.write(struct.pack(">ffffffffffiiiii", self.Head_q, self.Head_qd, self.Head_tau, self.Head_kp, self.Head_kd, self.waist_q, self.waist_qd, self.waist_tau, self.waist_kp, self.waist_kd, self.reserved1, self.reserved2, self.reserved3, self.reserved4, self.reserved5))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != humanoid_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return humanoid_joint_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = humanoid_joint_command_t()
        self.L_Leg_q = struct.unpack('>6f', buf.read(24))
        self.R_Leg_q = struct.unpack('>6f', buf.read(24))
        self.L_Arm_q = struct.unpack('>4f', buf.read(16))
        self.R_Arm_q = struct.unpack('>4f', buf.read(16))
        self.L_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.R_Leg_qd = struct.unpack('>6f', buf.read(24))
        self.L_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.R_Arm_qd = struct.unpack('>4f', buf.read(16))
        self.L_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.R_Leg_tau = struct.unpack('>6f', buf.read(24))
        self.L_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.R_Arm_tau = struct.unpack('>4f', buf.read(16))
        self.L_Leg_kp = struct.unpack('>6f', buf.read(24))
        self.R_Leg_kp = struct.unpack('>6f', buf.read(24))
        self.L_Arm_kp = struct.unpack('>4f', buf.read(16))
        self.R_Arm_kp = struct.unpack('>4f', buf.read(16))
        self.L_Leg_kd = struct.unpack('>6f', buf.read(24))
        self.R_Leg_kd = struct.unpack('>6f', buf.read(24))
        self.L_Arm_kd = struct.unpack('>4f', buf.read(16))
        self.R_Arm_kd = struct.unpack('>4f', buf.read(16))
        self.Head_q, self.Head_qd, self.Head_tau, self.Head_kp, self.Head_kd, self.waist_q, self.waist_qd, self.waist_tau, self.waist_kp, self.waist_kd, self.reserved1, self.reserved2, self.reserved3, self.reserved4, self.reserved5 = struct.unpack(">ffffffffffiiiii", buf.read(60))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if humanoid_joint_command_t in parents: return 0
        tmphash = (0xc4e16b6612954242) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if humanoid_joint_command_t._packed_fingerprint is None:
            humanoid_joint_command_t._packed_fingerprint = struct.pack(">Q", humanoid_joint_command_t._get_hash_recursive([]))
        return humanoid_joint_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", humanoid_joint_command_t._get_packed_fingerprint())[0]

