"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class external_control_command_t(object):

    __slots__ = ["robot_id", "enable_external_control", "action"]

    __typenames__ = ["string", "int32_t", "float"]

    __dimensions__ = [None, None, [21]]

    def __init__(self):
        self.robot_id = ""
        """
        机器人标识（用于标记目标机器人）
        LCM Type: string
        """

        self.enable_external_control = 0
        """
        控制标志
        LCM Type: int32_t
        """

        self.action = [ 0.0 for dim0 in range(21) ]
        """
        1=开始外部控制, 0=结束外部控制
        外部控制的action（21维：12腿+9臂）
        LCM Type: float[21]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(external_control_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __robot_id_encoded = self.robot_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_id_encoded)+1))
        buf.write(__robot_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.enable_external_control))
        buf.write(struct.pack('>21f', *self.action[:21]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != external_control_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return external_control_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = external_control_command_t()
        __robot_id_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_id = buf.read(__robot_id_len)[:-1].decode('utf-8', 'replace')
        self.enable_external_control = struct.unpack(">i", buf.read(4))[0]
        self.action = struct.unpack('>21f', buf.read(84))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if external_control_command_t in parents: return 0
        tmphash = (0x876baa19debca01d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if external_control_command_t._packed_fingerprint is None:
            external_control_command_t._packed_fingerprint = struct.pack(">Q", external_control_command_t._get_hash_recursive([]))
        return external_control_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", external_control_command_t._get_packed_fingerprint())[0]

